name: CI Pipeline

on:
  push:
    branches: [ '*' ]  # This will run on all branches
  pull_request:
    branches: [ '*' ]  # This will also run on pull requests to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Using Python 3.9 which is stable with these dependencies
    - name: Clear pip cache
      run: |
        pip cache purge
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt
    - name: List directory contents
      run: |
        pwd
        ls -la
        echo "Tests directory contents:"
        ls -la tests/
    - name: Run tests with coverage
      run: |
        # Set PYTHONPATH to include the project root
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        # Run tests with verbose output
        python -m pytest tests/ -v --cov=. --cov-report=xml
  
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: coverage.xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: coverage.xml    