name: CI Pipeline

on:
  push:
    branches: [ '*' ]  # This will run on all branches
  pull_request:
    branches: [ '*' ]  # This will also run on pull requests to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Using Python 3.9 which is stable with these dependencies
    - name: Clear pip cache
      run: |
        pip cache purge
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt
    - name: Run tests with coverage
      run: |
        pytest --cov=. --cov-report=xml
  